### PR TITLE
Add website name to CSS filename

### PR DESCRIPTION
**Pull request by TotalCaesar659**
It will be more comfortable fo those who collect many website themes not to rename it.

### CODE REVIEW

**Comment by blyad2137** [comment]
When you install it like a normal human being it's named properly:
`
@name           PCGamingWiki - Dark Theme
@namespace      github.com/blyad2137/pcgamingwiki-dark-theme
`

Just click install on readme.md or click on `raw` when looking at the code.

**Comment by TotalCaesar659** [comment]
I told not about **already installed** style that has "PCGamingWiki - Dark Theme" in Stylus list, I told about its **filename**, so this property @name you told about is beside the point.
I have large collection of many downloaded user CSS files on my PC, and many of them have good filename with website. For example:
https://github.com/RaitaroH/YouTube-DeepDark - **YouTubeDeepDarkMaterial.user.css**
https://github.com/StylishThemes/GitHub-Dark - **github-dark.user.css**
https://github.com/StylishThemes/Wikipedia-Dark - **wikipedia-dark.user.css**
This filename doesn't have "pcgamingwiki", just "dark-theme.user.css". And for knowing what's the site this CSS for, I have to open it and see this property. It's not so comfortable as would be (if you need to install it, send it to a friend etc.). And I proposed the enhancement for anyone else who downloads it - just see the website in the filename without opening or installing it.
So please read carefully before throw around words as "like a normal human being", this is not the best option for discussion.

**Comment by blyad2137** [comment]
Well, if thats the case. I just use `dark-theme.user.css` for convenience reasons, as to edit as least as possible lines at `readme.md` while copying the structure of it.
I guess changing one more line shouldn't hurt.

**Comment by TotalCaesar659** [comment]
Thank you very much for merging this, all CSS collectors will be grateful :-)

**Pull request merged**
